baseURL = 'https://bkleinen.github.io'

languageCode = 'en-us'
title = 'Prof. Dr. Barne Kleinen'

# sectionPagesMenu = "main"
theme = "greenpage"
enableGitInfo = true
canonifyURLs = true
ignoreFiles = ['README\.MD$', 'readme\.md$']
staticDir2 = ['static-snippets']
[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

[params]
  subTitle = 'Website of Prof. Dr. Barne Kleinen, Professor for '
  logoTitle = 'Programming and Web Technology @ IMI'
  serverencoding = "UTF-8"
  generatedLinks = true # set this to false to detect unlinked pages
  zoomBK = "https://htw-berlin.zoom.us/j/3165395630"
  mainProductionURL = 'https://home.htw-berlin.de/~kleinen'
  math = false
# rss feed
# https://gohugo.io/templates/rss/#the-embedded-rssxml
# https://gohugo.io/templates/rss/
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
languageCode = 'en-us'
rssLimit =  10
[ params.author ]
  name = 'Barne Kleinen'

# disableKinds = ['taxonomy', 'term']
[permalinks]
   courses = "/material/courses/:slug/"
   tools = "/material/tools/:slug/"
   tags = "/material/tags/:slug/"

