name: Deploy Staging

on:
  push:
    branches:
      - main  # Set a branch to deploy
    tags-ignore:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
      - name: Install Bootstrap with npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          cd hugo
          npm install
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Write gitinfo file
        run: bin/hugo_deployment/gitversion.sh ${{ github.ref }} ${{ github.sha }} "${{ github.workflow }}"
      - name: Build Hugo Site
        run: |
          hugo --source hugo  --minify --environment staging
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy to Staging on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN_PROGWEBTEC }}
          external_repository: bkleinen/staging
          publish_dir: ./hugo/public
          publish_branch: hugo_staging
          commit_message: ${{ github.event.head_commit.message }}
          #full_commit_message: ${{ github.event.head_commit.message }}

#      - name: Push to Staging website
#        uses: cpina/github-action-push-to-another-repository@main
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.OTHER_TOKEN }}
#        with:
#          source-directory: 'hugo/public'
#          destination-github-username: 'bkleinen'
#          destination-repository-name: 'staging'
#          user-email: barne.kleinen@htw-berlin.de
#          target-branch: hugo_staging
